- name: Demo on facts 
  hosts: PROD  
  tasks:  
    - name: Priniting a fact
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Priniting the mac address
      ansible.builtin.debug:
        msg: "{{ ansible_default_ipv4.macaddress }}"