- name: Demo on variables 
  hosts: all  
  tasks:
    - name: Run Shell Command 
      shell: uptime
      register: OUT 
    
    - name: Printing the Output of uptime 
      debug: 
        msg: The value of exit code is {{ OUT.rc }} and std out is {{ OUT.stdout }}
