- name: Check whether tomcat is running or not 
  hosts: all  
  tasks:
    - name: Check tomcat is running or not 
      shell: ps -ef |grep java | grep -v grep
      register: OUT 
      ignore_errors: yes 
    
    - name: Starting tomcat 
      debug: 
        msg: Starting Tomcat 